# Generated by Django 5.1.1 on 2024-10-05 10:59

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('parent_id', models.IntegerField()),
                ('node_name_en', models.CharField(default='', max_length=200)),
                ('node_name_fa', models.CharField(max_length=200)),
                ('old_id', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('headers'), models.Model),
        ),
        migrations.AddField(
            model_name='menustree',
            name='headers',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_tree_app.headers'),
        ),
    ]
