# Generated by Django 5.1.1 on 2024-09-18 07:57

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenusTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('parent_id', models.IntegerField()),
                ('node_name_en', models.CharField(default='', max_length=200)),
                ('node_name_fa', models.CharField(max_length=200)),
                ('img_url', models.CharField(blank=True, max_length=250, null=True)),
                ('version', models.IntegerField(default=1)),
                ('node_type_name', models.CharField(blank=True, max_length=254, null=True)),
                ('level', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, default='A', max_length=10)),
                ('is_new', models.BooleanField(default=False)),
                ('node_type_config_name', models.CharField(blank=True, max_length=255)),
                ('node_type_enum_id', models.IntegerField(default=0)),
                ('node_type_config_id', models.IntegerField(default=0)),
                ('fault_excel_info', models.TextField(blank=True)),
                ('node_type_feature_name', models.TextField(blank=True)),
                ('node_type_config_enum_id', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('menus'), models.Model),
        ),
    ]
