# Generated by Django 5.1.1 on 2024-09-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='agency_code',
        ),
        migrations.RemoveField(
            model_name='users',
            name='agency_name',
        ),
    ]
