# Generated by Django 5.1.1 on 2024-10-05 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0002_headers_menustree_headers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menustree',
            name='headers',
        ),
        migrations.AddField(
            model_name='headers',
            name='tree',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_tree_app.menustree'),
        ),
    ]
