# Generated by Django 5.1.1 on 2024-09-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0002_remove_users_agency_code_remove_users_agency_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='city',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_new_user',
        ),
        migrations.RemoveField(
            model_name='users',
            name='os_status',
        ),
        migrations.RemoveField(
            model_name='users',
            name='state',
        ),
        migrations.RemoveField(
            model_name='users',
            name='work_phone',
        ),
        migrations.AddField(
            model_name='users',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='mobile'),
        ),
    ]
