# Generated by Django 5.1.1 on 2024-09-18 08:30

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0002_menustree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('node_name_en', models.CharField(default='', max_length=200)),
                ('node_name_fa', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('company'), models.Model),
        ),
        migrations.AddField(
            model_name='menustree',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicle_tree_app.company'),
            preserve_default=False,
        ),
    ]
