# Generated by Django 5.1.1 on 2024-09-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0003_company_menustree_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menustree',
            old_name='Company',
            new_name='company',
        ),
    ]
