# Generated by Django 5.1.1 on 2024-10-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0003_remove_menustree_headers_headers_tree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headers',
            old_name='tree',
            new_name='menutree',
        ),
    ]
