# Generated by Django 5.1.1 on 2024-09-18 05:30

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0003_remove_users_address_remove_users_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenusTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('parent_id', models.IntegerField()),
                ('node_name_en', models.CharField(default='', max_length=200)),
                ('node_name_fa', models.CharField(max_length=200)),
                ('node_type_name', models.CharField(blank=True, max_length=254)),
                ('level', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, default='A', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('menus'), models.Model),
        ),
    ]
