# Generated by Django 5.1.1 on 2024-10-08 05:56

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0004_rename_tree_headers_menutree'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('fault_detail_excel_name', models.CharField()),
                ('v', models.CharField(max_length=255)),
                ('p', models.JSONField(default=dict)),
                ('node_enum_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_enum_name', to='vehicle_tree_app.menustree')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('FaultMap'), models.Model),
        ),
    ]
