# Generated by Django 5.1.1 on 2024-10-09 12:21

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0005_faultmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('node_type_config_name', models.CharField(blank=True, max_length=255)),
                ('node_type_config_id', models.IntegerField(default=0)),
                ('node_type_config_enum_id', models.IntegerField(default=0)),
                ('node_type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_node_name', to='vehicle_tree_app.menustree')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('Configtype'), models.Model),
        ),
    ]
