# Generated by Django 5.1.1 on 2024-10-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0006_configtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configtype',
            name='node_type_config_enum_id',
        ),
    ]
