# Generated by Django 5.1.1 on 2024-09-18 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0006_alter_menustree_company_alter_menustree_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menustree',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='vehicle_tree_app.company'),
        ),
        migrations.AlterField(
            model_name='menustree',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle_tree_app.vehicle'),
        ),
    ]
