# Generated by Django 5.1.1 on 2024-10-12 06:08

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0007_remove_configtype_node_type_config_enum_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetEnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('reset_enum_name', models.CharField(blank=True)),
                ('reset_enum_id', models.IntegerField(blank=True, null=True)),
                ('node_enum_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enum_name', to='vehicle_tree_app.menustree')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('ResetEnum'), models.Model),
        ),
    ]
