# Generated by Django 5.1.1 on 2024-09-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0007_alter_menustree_company_alter_menustree_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='parent_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
