# Generated by Django 5.1.1 on 2024-09-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0008_company_parent_id_vehicle_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='mobile',
        ),
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=20, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='users',
            name='code',
            field=models.CharField(max_length=4, null=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='users',
            name='expired_code',
            field=models.CharField(max_length=4, null=True, verbose_name='expired_code'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_new_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='os_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='phone_number'),
        ),
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='state'),
        ),
    ]
