# Generated by Django 5.1.1 on 2024-09-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tree_app', '0010_remove_users_address_remove_users_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menustree',
            name='level',
        ),
        migrations.RemoveField(
            model_name='menustree',
            name='version',
        ),
        migrations.AlterField(
            model_name='menustree',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='vehicle_tree_app.company'),
        ),
        migrations.AlterField(
            model_name='menustree',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle_tree_app.vehicle'),
        ),
    ]
